export const artists = [
    "frah quintale", 
    "marracash", 
    "blanco", 
    "carl brave",
    "calcutta",
    "francesco guccini",
    "freak antoni",
    "claudio fucci",
    "pacifico",
    "vinicio capossela",
    "fred buscaglione",
    "alberto fortis",
    "luigi tenco",
    "elisa",
    "mariano deidda",
    "cristiano de andré",
    "gino paoli",
    "massimo bubola",
    "nino ferrer",
    "lalli",
    "franco battiato",
    "piero ciampi",
    "samuele bersani",
    "enzo jannacci",
    "massimo riva",
    "francesco de gregori",
    "lucio battisti",
    "sergio caputo",
    "francesco baccini",
    "bobby solo",
    "toto cutugno",
    "renato rascel",
    "nada",
    "alice",
    "riccardo fogli",
    "al bano",
    "umberto tozzi",
    "luca barbarossa",
    "giorgia",
    "francesco renga",
    "michele zarrillo",
    "chiara iezzi",
    "paola iezzi",
    "paolo vallesi",
    "dolcenera",
    "biagio antonacci",
    "luca carboni",
    "paolo conte",
    "alex britti",
    "irene grandi",
    "mariella nava",
    "ivana spagna",
    "loredana bertè",
    "raf",
    "bruno lauzi",
    "sergio bruni",
    "pino donaggio",
    "alessandro bono",
    "ivan graziani",
    "mango",
    "franco califano",
    "bungaro",
    "mario venuti",
    "adriano pappalardo",
    "neffa",
    "andrea mingardi",
    "daniele groff",
    "sergio cammariere",
    "andrea mirò",
    "silvia salemi",
    "fiordaliso",
    "gianluca grignani",
    "mino reitano",
    "marco armani",
    "fred bongusto",
    "marina rei",
    "omar pedrini",
    "gerardina trovato",
    "max gazzè",
    "giò di tonno",
    "massimo di cataldo",
    "gatto panceri",
    "enzo gragnaniello",
    "sandro giacobbe",
    "gianni bella",
    "alex baroni",
    "marisa sannia",
    "angelo branduardi",
    "niccolò fabi",
    "luca sepe",
    "alan sorrenti",
    "nino buonocore",
    "tullio de piscopo",
    "don backy",
    "donatella milani",
    "eduardo de crescenzo",
    "joe sentieri",
    "ivano fossati",
    "pierangelo bertoli",
    "oliviero malaspina",
    "gianmaria testa",
    "roby facchinetti",
    "dodi battaglia",
    "marco del freo",
    "gianna nannini",
    "ilaria porceddu",
    "edoardo bennato",
    "caparezza",
    "laura valente",
    "maria carta",
    "davide toffolo",
    "roberto vecchioni",
    "jo squillo",
    "miguel bosé",
    "cristina donà",
    "fabio concato",
    "pupo",
    "mario castelnuovo",
    "tony tammaro",
    "elio",
    "paolo benvegnù",
    "leano morelli",
    "herbert pagani",
    "alessandro errico",
    "maurizio lauzi",
    "piero marras",
    "jenny sorrenti",
    "max pezzali",
    "giovanni capurro",
    "ivan segreto",
    "marco conidi",
    "franco fanigliulo",
    "riccardo marasco",
    "goran kuzminac",
    "shel shapiro",
    "peter van wood",
    "franco fasano",
    "rosa balistreri",
    "ciro sebastianelli",
    "riccardo del turco",
    "pino marino",
    "umberto palazzo",
    "garbo",
    "tony esposito",
    "eugenio bennato",
    "massimo zamboni",
    "alberto camerini",
    "marco ferradini",
    "nikki",
    "carla bruni",
    "simone cristicchi",
    "kaballà",
    "odoardo spadaro",
    "betty vittori",
    "andrea ra",
    "ivan della mea",
    "alfredo bandelli",
    "otello profazio",
    "giovanna marini",
    "paolo pietrangeli",
    "cristiano godano",
    "mario cappello",
    "oscar prudente",
    "max manfredi",
    "pippo pollina",
    "leda battisti",
    "dario vergassola",
    "rinaldo prandoni",
    "giorgio canali",
    "brigantony",
    "nico fidenco",
    "roby santini",
    "diego mancino",
    "niccolò bossini",
    "stefano rosso",
    "meg",
    "fausto amodei",
    "federico fiumani",
    "francesco fiore",
    "ghibli",
    "riccardo sinigallia",
    "alvaro amici",
    "lino toffolo",
    "andrea chimenti",
    "federico salvatore",
    "sergio laccone",
    "mao",
    "cisco",
    "mauro di maggio",
    "annalisa minetti",
    "rudi assuntino",
    "laura luca",
    "walter valdi",
    "alfio antico",
    "andrea parodi",
    "giorgio bracardi",
    "lucio quarantotto",
    "dario aspesani",
    "claudio chieffo",
    "max parodi",
    "brando",
    "erriquez",
    "gianni togni",
    "mario lavezzi",
    "grido",
    "luigi grechi",
    "dargen d'amico",
    "gianni fiorellino",
    "lu colombo",
    "laura pausini",
    "juri camisasca",
    "gipo farassino",
    "edoardo vianello",
    "francesco magni",
    "joe barbieri",
    "gianni meccia",
    "paolo barabani",
    "marco luberti",
    "benito urgu",
    "corrado rustici",
    "anselmo genovese",
    "umberto maria giardini",
    "giorgio conte",
    "teresa de sio",
    "gino marielli",
    "enzo carella",
    "umberto balsamo",
    "sandro petrone",
    "lele battista",
    "eugenio finardi",
    "bobo rondelli",
    "massimo bizzarri",
    "zucchero fornaciari",
    "federico zampaglione",
    "mimmo locasciulli",
    "enrico nascimbeni",
    "riccardo azzurri",
    "enzo malepasso",
    "alessio bonomo",
    "al rangone",
    "manuel de peppe",
    "clem sacco",
    "romolo balzani",
    "giorgio faletti",
    "mario biondi",
    "mauro lusini",
    "maria monti",
    "beppe cardile",
    "enrico capuano",
    "guido de angelis",
    "maurizio de angelis",
    "armando gill",
    "andrea agresti",
    "stefano rossi crespi",
    "ghemon",
    "gigi d'alessio",
    "al castellana",
    "roberto murolo",
    "pippo starnazza",
    "alexia",
    "david riondino",
    "luigi maieron",
    "egisto malfatti",
    "marco chiarelli",
    "mimmo di francia",
    "mariangela",
    "enzo del re",
    "alessio lega",
    "roberta faccani",
    "samuel",
    "alan wurzburger",
    "vincenzo spampinato",
    "luciano ravasio",
    "ennio rega",
    "gennaro pasquariello",
    "el pasador",
    "enzo maolucci",
    "graziano romani",
    "mara cantoni",
    "massimo dorati",
    "leone di lernia",
    "cesare basile",
    "anna calemme",
    "carlo muratori",
    "pino scotto",
    "renzo zenobi",
    "ugolino",
    "diana tejera",
    "edoardo de angelis",
    "flegias",
    "gian pieretti",
    "lucio dalla",
    "dave rodgers",
    "bracco di graci",
    "lorenzo zecchino",
    "marcello pieri",
    "giampiero artegiani",
    "erminio sinni",
    "daniela colace",
    "daniele fossati",
    "fedele boccassini",
    "fabrizio consoli",
    "umberto bindi",
    "riccardo bellei",
    "gianfranco manfredi",
    "mirko petrini",
    "gala",
    "enrico boccadoro",
    "angela milanese",
    "andrea liberovici",
    "renzo arbore",
    "valerio liboni",
    "riccardo cocciante",
    "rocco granata",
    "mario guarnera",
    "tony cucchiara",
    "santino rocchetti",
    "gianni mauro",
    "roberto soffici",
    "stefano tosi",
    "roberta d'angelo",
    "anna melato",
    "rinaldo del monte",
    "alessandro",
    "ron",
    "manuele pepe",
    "antonella bottazzi",
    "federico sirianni",
    "musica per bambini",
    "valentina gautier",
    "franz campi",
    "marco carena",
    "rodolfo de angelis",
    "aldo donati",
    "silvano spadaccino",
    "stefano scandaletti",
    "mike francis",
    "paolo frescura",
    "carlo gigli",
    "patrizio sandrelli",
    "ernesto bassignano",
    "giorgio lo cascio",
    "giuliano palma",
    "silverio pisu",
    "chiara grillo",
    "vasco rossi",
    "mariadele",
    "alessandro orlando graziano",
    "toni santagata",
    "tito schipa jr.",
    "neja",
    "rino gaetano",
    "renato carosone",
    "lucilla galeazzi",
    "antonella ruggiero",
    "giorgio bettinelli",
    "giosy cento",
    "gianluca capozzi",
    "danilo amerio",
    "piero brega",
    "filippo malatesta",
    "paola turci",
    "enzo draghi",
    "giovanni alamia",
    "flavio giurato",
    "maria rita viaggi",
    "luca madonia",
    "roberto carrino",
    "nicola maldacea",
    "tony colombo",
    "lara martelli",
    "paolo belli",
    "alborosie",
    "davide de marinis",
    "gianni marà",
    "wanda montanelli",
    "maria sole",
    "giovanni rondelli",
    "nicoletta bauce",
    "michele pecora",
    "paolo mosca",
    "fausto rossi",
    "carlo marangon",
    "walter foini",
    "dario gay",
    "gaspare bernardi",
    "stefania orlando",
    "raiz",
    "dellera",
    "anonimo italiano",
    "carlo d'angiò",
    "nello daniele",
    "eros ramazzotti",
    "rosario di bella",
    "gabrè",
    "clara moroni",
    "franca lai",
    "berardo cantalamessa",
    "angelo avarello",
    "donatella rettore",
    "federico poggipollini",
    "sergio endrigo",
    "mimmo cavallo",
    "giuseppe cionfoli",
    "allegra lusini",
    "marcello marrocchi",
    "giangilberto monti",
    "enrico sognato",
    "filippo schisano",
    "marcello de angelis",
    "sergio bassi",
    "cristiano malgioglio",
    "fabrizio casalino",
    "nek",
    "niccolò agliardi",
    "piero giorgetti",
    "costa",
    "gino santercole",
    "luciano rossi",
    "beppe chierici",
    "dino lenny",
    "pierfrancesco poggi",
    "il guardiano del faro",
    "malika ayane",
    "pino d'angiò",
    "massimiliano cattapani",
    "goffredo canarini",
    "roberto tardito",
    "mitzi amoroso",
    "franco morgia",
    "mauro pelosi",
    "fratello metallo",
    "simon luca",
    "rudy marra",
    "pino daniele",
    "luciano ligabue",
    "claudio daiano",
    "stefano zarfati",
    "the niro",
    "jovanotti",
    "tony blescia",
    "renato zero",
    "giorgio zito",
    "morgan",
    "nino minieri",
    "elena ledda",
    "claudio rocchi",
    "grazia di michele",
    "peppe voltarelli",
    "miko",
    "ivan cattaneo",
    "massimo morsello",
    "sebastiano occhino",
    "franco simone",
    "jerico",
    "pierpaolo capovilla",
    "gianni celeste",
    "fabrizio de andré",
    "vincent rose",
    "luciano ceri",
    "massimo priviero",
    "CALCUTTA",
    "gian piero alloisio",
    "paco d'alcatraz",
    "sergio agostini",
    "michele straniero",
    "margot",
    "alfio finetti",
    "aleandro baldi",
    "claudio baglioni",
    "miro",
    "vito paradiso",
    "marco masini",
    "laura fedele",
    "antonio infantino",
    "natale galletta",
    "domenico modugno",
    "edda",
    "toni malco",
    "enzo guarini",
    "corrado sannucci",
    "johnson righeira",
    "luca bonaffini",
    "giovanni nuti",
    "antonello venditti",
    "emanuel lo",
    "renato pareti",
    "mia martini",
    "andrea mazzacavallo",
    "enzo di domenico",
    "riccardo donna",
    "roby crispiano",
    "piero pelù",
    "renato brioschi",
    "roberto kunstler",
    "filippo marcheggiani",
    "fabio koryu calabrò",
    "carmen consoli",
    "fabrizio poggi",
    "frankie hi-nrg mc",
    "neffa",
    "caparezza",
    "joe cassano",
    "inoki",
    "lucariello",
    "fabri fibra",
    "la pina",
    "el presidente",
    "rischio",
    "lou x",
    "kaos",
    "jake la furia",
    "deda",
    "zampa",
    "don joe",
    "mastafive",
    "principe",
    "jap",
    "tsu",
    "babaman",
    "c.u.b.a. cabbal",
    "taiyo yamanouchi",
    "grido",
    "dargen d'amico",
    "chef ragoo",
    "vincenzo da via anfossi",
    "gopher",
    "ghemon",
    "kento",
    "left side",
    "herman medrano",
    "thema",
    "danno",
    "metal carter",
    "supa",
    "space one",
    "kiave",
    "rido mc",
    "'o zulù",
    "franco negrè",
    "ensi",
    "piotta",
    "jovanotti",
    "guè",
    "mc giaime",
    "dj gruff",
    "ice one",
    "ape",
    "amir",
    "sparo manero",
    "marya",
    "mistaman",
    "turi",
    "speaker cenzou",
    "noyz narcos",
    "bassi maestro",
    "j-ax",
    "vacca",
    "tormento",
    "dj enzo",
    "caneda",
    "francesco paura",
    "primo brown",
    "gel",
    "coez",
    "murubutu",
    "dj lugi",
    "luchè",
    "frank siciliano",
    "lele blade",
    "frankie hi-nrg mc",
    "neffa",
    "caparezza",
    "inoki",
    "lucariello",
    "fabri fibra",
    "la pina",
    "el presidente",
    "rischio",
    "lou x",
    "kaos",
    "marracash",
    "jake la furia",
    "deda",
    "zampa",
    "don joe",
    "mastafive",
    "principe",
    "jap",
    "tsu",
    "babaman",
    "jesto",
    "c.u.b.a. cabbal",
    "taiyo yamanouchi",
    "jack the smoker",
    "grido",
    "dargen d'amico",
    "chef ragoo",
    "vincenzo da via anfossi",
    "gopher",
    "ghemon",
    "kento",
    "left side",
    "herman medrano",
    "thema",
    "danno",
    "metal carter",
    "supa",
    "space one",
    "kiave",
    "rayden",
    "rido mc",
    "'o zulù",
    "franco negrè",
    "ensi",
    "piotta",
    "asher kuno",
    "jovanotti",
    "nesli",
    "gué pequeno",
    "dj gruff",
    "ice one",
    "ape",
    "amir",
    "sparo manero",
    "marya",
    "mistaman",
    "turi",
    "speaker cenzou",
    "noyz narcos",
    "bassi maestro",
    "j-ax",
    "vacca",
    "tormento",
    "mondo marcio",
    "salmo",
    "dj enzo",
    "raige",
    "caneda",
    "santo trafficante",
    "francesco paura",
    "emis killa",
    "rancore",
    "clementino",
    "primo brown",
    "gel",
    "fedez",
    "coez",
    "moreno",
    "murubutu",
    "gemitaiz",
    "madman",
    "nitro",
    "egreen",
    "dj lugi",
    "duke montana",
    "luchè",
    "sfera ebbasta",
    "irama",
    "mecna",
    "ghali",
    "laïoung",
    "izi",
    "mostro",
    "rkomi",
    "shade",
    "willie peyote",
    "ntò",
    "skuba libre",
    "mudimbi",
    "enigma",
    "tedua",
    "ernia",
    "carl brave",
    "sick luke",
    "frank siciliano",
    "mezzosangue",
    "capo plaza",
    "frah quintale",
    "ketama126",
    "vegas jones",
    "cranio randagio",
    "anastasio",
    "franco126",
    "livio cori",
    "lazza",
    "lanz khan",
    "mike fc",
    "dani faiv",
    "myss keta",
    "jamil",
    "signor k",
    "lowlow",
    "lele blade",
    "massimo pericolo",
    "junior cally",
    "tha supreme",
    "dutch nazari",
    "shiva",
    "fasma",
    "giaime",
    "nayt",
    "anna",
    "chadia rodríguez",
    "claver gold",
    "gianni bismark",
    "mr. rain",
    "geolier",
    "drefgold",
    "og eastbull",
    "hell raton",
    "random",
    "boro boro",
    "biondo",
    "ma rue",
    "suarez",
    "vale lambo",
    "rose villain",
    "yung snapp",
    "rosa chemical",
    "zoda",
    "coco",
    "nicola siciliano",
    "mv killa",
    "madame",
    "nerone",
    "axos",
    "roshelle",
    "alfa",
    "mambolosco",
    "pretty solero",
    "villabanks",
    "il tre",
    "bresh",
    "rondodasosa",
    "leon faun",
    "tredici pietro",
    "rhove",
    "tutti fenomeni",
    "paky",
    "francesco guccini",
    "freak antoni",
    "claudio fucci",
    "vinicio capossela",
    "alberto fortis",
    "elisa",
    "mariano deidda",
    "cristiano de andré",
    "gino paoli",
    "massimo bubola",
    "lalli",
    "samuele bersani",
    "davide van de sfroos",
    "enzo jannacci",
    "carlo fava",
    "francesco de gregori",
    "sergio caputo",
    "francesco baccini",
    "bobby solo",
    "toto cutugno",
    "alice",
    "riccardo fogli",
    "al bano",
    "umberto tozzi",
    "luca barbarossa",
    "francesco renga",
    "michele zarrillo",
    "chiara iezzi",
    "paola iezzi",
    "paolo vallesi",
    "dolcenera",
    "claudio lolli",
    "biagio antonacci",
    "luca carboni",
    "paolo conte",
    "alex britti",
    "irene grandi",
    "mariella nava",
    "ivana spagna",
    "loredana bertè",
    "raf",
    "bruno lauzi",
    "lighea",
    "mango",
    "franco califano",
    "bungaro",
    "linda valori",
    "mario venuti",
    "adriano pappalardo",
    "neffa",
    "andrea mingardi",
    "daniele groff",
    "sergio cammariere",
    "andrea mirò",
    "silvia salemi",
    "fiordaliso",
    "gianluca grignani",
    "daniele silvestri",
    "marco armani",
    "fred bongusto",
    "marina rei",
    "omar pedrini",
    "gerardina trovato",
    "max gazzè",
    "giò di tonno",
    "massimo di cataldo",
    "gatto panceri",
    "enzo gragnaniello",
    "sandro giacobbe",
    "gianni bella",
    "alex baroni",
    "povia",
    "angelo branduardi",
    "niccolò fabi",
    "luca sepe",
    "alan sorrenti",
    "nino buonocore",
    "tullio de piscopo",
    "don backy",
    "eduardo de crescenzo",
    "ivano fossati",
    "oliviero malaspina",
    "gianmaria testa",
    "roby facchinetti",
    "dodi battaglia",
    "marco del freo",
    "gianna nannini",
    "ilaria porceddu",
    "edoardo bennato",
    "caparezza",
    "laura valente",
    "davide toffolo",
    "roberto vecchioni",
    "max de angelis",
    "jo squillo",
    "miguel bosé",
    "cristina donà",
    "fabio concato",
    "pupo",
    "mario castelnuovo",
    "tony tammaro",
    "giovanni lindo ferretti",
    "elio",
    "marjorie biondo",
    "paolo benvegnù",
    "leano morelli",
    "alessandro errico",
    "maurizio lauzi",
    "piero marras",
    "jenny sorrenti",
    "max pezzali",
    "ivan segreto",
    "marco conidi",
    "riccardo marasco",
    "goran kuzminac",
    "shel shapiro",
    "franco fasano",
    "ciro sebastianelli",
    "pino marino",
    "umberto palazzo",
    "garbo",
    "tony esposito",
    "eugenio bennato",
    "massimo zamboni",
    "alberto camerini",
    "marco ferradini",
    "nikki",
    "carla bruni",
    "tricarico",
    "luca dirisio",
    "simone cristicchi",
    "riccardo maffoni",
    "betty vittori",
    "andrea ra",
    "ivan della mea",
    "giovanna marini",
    "paolo pietrangeli",
    "cristiano godano",
    "l'aura",
    "oscar prudente",
    "max manfredi",
    "pippo pollina",
    "leda battisti",
    "dario vergassola",
    "rinaldo prandoni",
    "giorgio canali",
    "roberto angelini",
    "brigantony",
    "roby santini",
    "diego mancino",
    "giuliano sangiorgi",
    "meg",
    "amalia gré",
    "fausto amodei",
    "federico fiumani",
    "patrizia laquidara",
    "ghibli",
    "riccardo sinigallia",
    "lino toffolo",
    "andrea chimenti",
    "federico salvatore",
    "sergio laccone",
    "mao",
    "cisco",
    "mauro di maggio",
    "annalisa minetti",
    "alfio antico",
    "andrea parodi",
    "lucio quarantotto",
    "claudio chieffo",
    "max parodi",
    "brando",
    "erriquez",
    "gianni togni",
    "mario lavezzi",
    "grido",
    "luigi grechi",
    "dargen d'amico",
    "laura pausini",
    "manuel agnelli",
    "edoardo vianello",
    "francesco magni",
    "irene fornaciari",
    "joe barbieri",
    "paolo barabani",
    "marco luberti",
    "benito urgu",
    "corrado rustici",
    "umberto maria giardini",
    "valeria rossi",
    "teresa de sio",
    "gino marielli",
    "enzo carella",
    "umberto balsamo",
    "sandro petrone",
    "lele battista",
    "eugenio finardi",
    "bobo rondelli",
    "francesco sarcina",
    "massimo bizzarri",
    "zucchero fornaciari",
    "federico zampaglione",
    "mimmo locasciulli",
    "enrico nascimbeni",
    "riccardo azzurri",
    "alessio bonomo",
    "bugo",
    "clem sacco",
    "giorgio faletti",
    "mario biondi",
    "beppe cardile",
    "enrico capuano",
    "maurizio de angelis",
    "andrea agresti",
    "stefano rossi crespi",
    "ghemon",
    "gigi d'alessio",
    "al castellana",
    "alexia",
    "david riondino",
    "luigi maieron",
    "marco chiarelli",
    "momo",
    "mariangela",
    "enzo del re",
    "nevio",
    "alessio lega",
    "roberta faccani",
    "luigi libra",
    "samuel",
    "alan wurzburger",
    "pier cortese",
    "vincenzo spampinato",
    "luciano ravasio",
    "ennio rega",
    "carolina benvenga",
    "graziano romani",
    "mara cantoni",
    "leone di lernia",
    "andrea rivera",
    "cesare basile",
    "anna calemme",
    "carlo muratori",
    "luca faggella",
    "pino scotto",
    "tonj acquaviva",
    "renzo zenobi",
    "diana tejera",
    "edoardo de angelis",
    "flegias",
    "lucio dalla",
    "bracco di graci",
    "marcello pieri",
    "giampiero artegiani",
    "erminio sinni",
    "daniela colace",
    "daniele fossati",
    "fabrizio consoli",
    "riccardo bellei",
    "gianfranco manfredi",
    "mirko petrini",
    "gala",
    "enrico boccadoro",
    "folco orselli",
    "angela milanese",
    "andrea liberovici",
    "renzo arbore",
    "riccardo cocciante",
    "gianni mauro",
    "roberta d'angelo",
    "rinaldo del monte",
    "ron",
    "musica per bambini",
    "valentina gautier",
    "franz campi",
    "aldo donati",
    "stefano scandaletti",
    "paolo frescura",
    "goodmorningboy",
    "ernesto bassignano",
    "giorgio lo cascio",
    "giuliano palma",
    "chiara grillo",
    "vasco rossi",
    "mariadele",
    "francesco bianconi",
    "alessandro orlando graziano",
    "mimosa campironi",
    "toni santagata",
    "neja",
    "marco bellotti",
    "renato carosone",
    "antonella ruggiero",
    "giorgio bettinelli",
    "giosy cento",
    "gianluca capozzi",
    "danilo amerio",
    "piero brega",
    "filippo malatesta",
    "paola turci",
    "enzo draghi",
    "flavio giurato",
    "giua",
    "maria rita viaggi",
    "luca madonia",
    "tony colombo",
    "alessio",
    "lara martelli",
    "paolo belli",
    "alborosie",
    "frank head",
    "jacopo troiani",
    "davide de marinis",
    "gianni marà",
    "veronica marchi",
    "wanda montanelli",
    "enrico giaretta",
    "giovanni rondelli",
    "michele pecora",
    "fabrizio moro",
    "gabriele lopez",
    "paolo mosca",
    "fausto rossi",
    "walter foini",
    "dario gay",
    "jeffrey jey",
    "gaspare bernardi",
    "stefania orlando",
    "raiz",
    "dellera",
    "anonimo italiano",
    "carlo d'angiò",
    "nello daniele",
    "eros ramazzotti",
    "rosario di bella",
    "gianni resta",
    "clara moroni",
    "franca lai",
    "marian trapassi",
    "irene nonis",
    "angelo avarello",
    "antonio maggio",
    "donatella rettore",
    "federico poggipollini",
    "sergio endrigo",
    "mimmo cavallo",
    "giuseppe cionfoli",
    "allegra lusini",
    "marcello marrocchi",
    "giangilberto monti",
    "enrico sognato",
    "filippo schisano",
    "marcello de angelis",
    "sergio bassi",
    "cristiano malgioglio",
    "marco parente",
    "fabrizio casalino",
    "nek",
    "tiziano ferro",
    "niccolò agliardi",
    "luciano rossi",
    "beppe chierici",
    "dino lenny",
    "pierfrancesco poggi",
    "malika ayane",
    "pino d'angiò",
    "marianna cataldi",
    "roberto tardito",
    "fabrizio coppola",
    "franco morgia",
    "mauro pelosi",
    "fratello metallo",
    "pino daniele",
    "roby rossini",
    "luciano ligabue",
    "daniele maggioli",
    "simona molinari",
    "stefano zarfati",
    "lubjan",
    "ania cecilia",
    "jovanotti",
    "tony blescia",
    "renato zero",
    "giorgio zito",
    "marco notari",
    "beatrice antolini",
    "dente",
    "matteo becucci",
    "morgan",
    "nino minieri",
    "elena ledda",
    "nesli",
    "claudio rocchi",
    "grazia di michele",
    "peppe voltarelli",
    "luciano caldore",
    "roberto casalino",
    "ivan cattaneo",
    "stefano tessadri",
    "sebastiano occhino",
    "franco simone",
    "jerico",
    "alessandro raina",
    "gianni celeste",
    "luciano ceri",
    "massimo priviero",
    "gian piero alloisio",
    "paco d'alcatraz",
    "michele straniero",
    "margot",
    "alfio finetti",
    "aleandro baldi",
    "claudio baglioni",
    "miro",
    "vito paradiso",
    "massimiliano d'ambrosio",
    "marco masini",
    "laura fedele",
    "antonio infantino",
    "natale galletta",
    "leo pari",
    "edda",
    "toni malco",
    "simone tomassini",
    "corrado sannucci",
    "johnson righeira",
    "luca bonaffini",
    "naïf hérin",
    "giovanni nuti",
    "antonello venditti",
    "flavio pirini",
    "emanuel lo",
    "renato pareti",
    "enzo di domenico",
    "luca napolitano",
    "j-ax",
    "giuliano dottori",
    "piero pelù",
    "debora petrina",
    "germano bonaveri",
    "roberto kunstler",
    "filippo marcheggiani",
    "immanuel casto",
    "carmen consoli",
    "fabrizio poggi",
    "carlo faiello",
    "nina zilli",
    "pierdavide carone",
    "amedeo minghi",
    "susanna parigi",
    "alessandro fiori",
    "andrea parodi",
    "tony maiello",
    "enrico ruggeri",
    "cesare cremonini",
    "gualtiero bertelli",
    "lello musella",
    "nando citarella",
    "roberta carrieri",
    "antonio buonomo",
    "corrado castellari",
    "marco ongaro",
    "adriano celentano",
    "paolo audino",
    "jacopo ratini",
    "grazia verasani",
    "silvia olari",
    "stefano giaccone",
    "saverio grandi",
    "vic vergeat",
    "marivana",
    "maler",
    "giovanni block",
    "vasco brondi",
    "valeria vaglio",
    "evasio muraro",
    "nathalie",
    "max meazza",
    "gaio chiocchio",
    "fabrizio zanotti",
    "raphael gualazzi",
    "giorgio laneve",
    "serena abrami",
    "gianluca de rubertis",
    "virginio",
    "annalisa",
    "alessandro mannarino",
    "daniele brusaschetto",
    "massimiliano larocca",
    "marcello colasurdo",
    "chiara canzian",
    "gianni siviero",
    "antonietta laterza",
    "brunori sas",
    "maurizio capone",
    "matilde politi",
    "franco ricciardi",
    "mauro nardi",
    "nicola di bari",
    "aldo tagliapietra",
    "virgilio savona",
    "cristina d'avena",
    "wess",
    "mariano deidda",
    "eva robin's",
    "rocky roberts",
    "noa",
    "iva zanicchi",
    "nilla pizzi",
    "johnny dorelli",
    "tony renis",
    "peppino di capri",
    "mino vergnaghi",
    "tosca",
    "massimo ranieri",
    "fausto leali",
    "teo mammucari",
    "cinzia corrado",
    "lena biolcati",
    "laura bono",
    "cochi ponzoni",
    "mietta",
    "syria",
    "jenny b",
    "patty pravo",
    "franco fabbri",
    "fiorella mannoia",
    "roy paci",
    "raffaella carrà",
    "teddy reno",
    "milva",
    "ornella vanoni",
    "carlo marrale",
    "barbara cola",
    "rossella marcone",
    "gigi finizio",
    "nicola arigliano",
    "nicky nicolai",
    "federica felini",
    "linda valori",
    "veruska",
    "massimo modugno",
    "federico stragà",
    "alessandro safina",
    "luisa corna",
    "giò di tonno",
    "francesca schiavo",
    "jimmy fontana",
    "christian",
    "orietta berti",
    "rossana casale",
    "scialpi",
    "sabrina salerno",
    "enrico ghedi",
    "francesco facchinetti",
    "giampaolo bertuzzi",
    "massimo castellina",
    "loretta goggi",
    "tomas milian",
    "red canzian",
    "silvia mezzanotte",
    "antonella lualdi",
    "giancarlo guardabassi",
    "lelio luttazzi",
    "christian de sica",
    "mariano apicella",
    "peppino gagliardi",
    "heather parisi",
    "lorella cuccarini",
    "fiorella bini",
    "luisa zappa",
    "marco rancati",
    "danilo sacco",
    "michelle hunziker",
    "sandra mondaini",
    "andrea sacco",
    "alessandro mara",
    "adriana ruocco",
    "leandro barsotti",
    "marco guerzoni",
    "francesca chiara",
    "ricky gianco",
    "enrico montesano",
    "michael bublé",
    "moni ovadia",
    "massimo vecchi",
    "marinella",
    "memo remigi",
    "gianni pettenati",
    "pietra montecorvino",
    "lina sastri",
    "viola valentino",
    "leopoldo mastelloni",
    "pino campagna",
    "lando buzzanca",
    "vittorio matteucci",
    "petra magoni",
    "lara saint paul",
    "fabio lione",
    "mr. t-bone",
    "haiducii",
    "franz di cioccio",
    "narciso parigi",
    "edoardo nevola",
    "michele luppi",
    "antonino spadaccino",
    "dennis fantina",
    "fanny cadeo",
    "nico di palo",
    "billy more",
    "claudio lippi",
    "farida",
    "carmen villani",
    "corona",
    "ray lovelock",
    "cristina scabbia",
    "simone patrizi",
    "gianluigi cavallo",
    "tullio visioli",
    "antonio righetti",
    "amii stewart",
    "gianni lamagna",
    "laura freddi",
    "pippo franco",
    "oswald sattler",
    "mario merola",
    "george mcanthony",
    "laura chiatti",
    "veronica piris",
    "patrizia pellegrino",
    "babaman",
    "elisabetta viviani",
    "violante placido",
    "sabrina marinangeli",
    "jessica morlacchi",
    "massimiliano varrese",
    "naike rivelli",
    "irene lamedica",
    "daniele vit",
    "catherine spaak",
    "giorgio vanni",
    "chef ragoo",
    "paola folli",
    "ginevra di marco",
    "matteo branciamore",
    "franco mussida",
    "gianluca guidi",
    "elisabetta vezzani",
    "franco tozzi",
    "angela baraldi",
    "lillo",
    "irene fargo",
    "gennaro cosmo parlato",
    "patrizio buanne",
    "pamela petrarolo",
    "sir oliver skardy",
    "arianna",
    "beppe dettori",
    "paolo poli",
    "matthew lee",
    "franco oppini",
    "manuel frattini",
    "mara",
    "andrea balestri",
    "papa ricky",
    "barbara boncompagni",
    "serena rossi",
    "marco cocci",
    "lando fiorini",
    "p. lion",
    "claude barzotti",
    "andrea poltronieri",
    "dado",
    "massimo morini",
    "piero mazzocchetti",
    "peppe barra",
    "miranda martino",
    "irene d'areni",
    "jaka",
    "gazebo",
    "brusco",
    "alessandro haber",
    "francesca pettinelli",
    "angela cavagna",
    "moony",
    "dino sarti",
    "james senese",
    "nini salerno",
    "luca morino",
    "jasmine",
    "carmelo zappulla",
    "loredana maiuri",
    "francesco benigno",
    "nadia biondini",
    "marcella bella",
    "stefano centomo",
    "maurizio geri",
    "dora moroni",
    "madaski",
    "alex damiani",
    "donatella moretti",
    "gaetano curreri",
    "bruno illiano",
    "senhit",
    "charlie cinelli",
    "andrea del boca",
    "riz samaritano",
    "alina",
    "nicolò grimaldi",
    "milena manni",
    "rita forte",
    "marco bazzoni",
    "guidone",
    "luciana turina",
    "ghigo agosti",
    "rudy giovannini",
    "in-grid",
    "antonella bucci",
    "flavia astolfi",
    "caterina bueno",
    "michela coppa",
    "lorenza mario",
    "stefan fiori",
    "gianni morandi",
    "claudio celli",
    "eugenia foligatti",
    "aura d'angelo",
    "pietro ubaldi",
    "gloria piedimonte",
    "fiorella pierobon",
    "delia gualtiero",
    "francesco banti",
    "carmelo pagano",
    "francesco stranges",
    "gloriana",
    "angela luce",
    "paola pitagora",
    "caterina valente",
    "brunella borciani",
    "alessio colombini",
    "gerardo carmine gargiulo",
    "emanuela cortesi",
    "nico tirone",
    "alberto solfrini",
    "jacopo sarno",
    "carlotta",
    "francesca touré",
    "lisa fusco",
    "dino drusiani",
    "carmen amato",
    "daniela goggi",
    "ombretta colli",
    "antonella monetti",
    "alessandro mazzinghi",
    "dhany",
    "manuela villa",
    "matteo brancaleoni",
    "enrico musiani",
    "marco bonino",
    "chiara civello",
    "danilo brugia",
    "simona patitucci",
    "fernando proce",
    "gianni riso",
    "fabio treves",
    "benedetta valanzano",
    "sal da vinci",
    "valter brugiolo",
    "laura troschel",
    "cecilia chailly",
    "daniele vaschi",
    "gabriele fersini",
    "katia svizzero",
    "sara santostasi",
    "lady violet",
    "belsy",
    "elena castagnoli",
    "daniele battaglia",
    "adolfo margiotta",
    "pia velsi",
    "davide ferrario",
    "mariolino barberis",
    "adriana russo",
    "gegè telesforo",
    "minnie minoprio",
    "titti bianchi",
    "claudia vegliante",
    "olly",
    "mario trevi",
    "bernardo lanzetti",
    "roberto tiranti",
    "gianfranco gallo",
    "john foster",
    "emanuele asti",
    "ramona badescu",
    "alessio bertallot",
    "erika",
    "donella del monaco",
    "alberto testa",
    "francesco di giacomo",
    "lola ponce",
    "belen thomas",
    "marco morandi",
    "luciano rondinella",
    "andrea zanini",
    "morby",
    "chiara noschese",
    "mario castiglia",
    "tying tiffany",
    "stefano de sando",
    "bruno venturini",
    "maurizio arcieri",
    "ken laszlo",
    "denise faro",
    "laura marinoni",
    "cristina marocco",
    "elio pandolfi",
    "rosario miraggio",
    "carlo pierangeli",
    "manuela zanier",
    "carmine faraco",
    "eva poles",
    "andrea bruschi",
    "mina",
    "luca jurman",
    "silvia giordano",
    "gigi camedda",
    "bunna",
    "stefano palatresi",
    "gabriele grilli",
    "brunetta",
    "mara cubeddu",
    "alessio garavello",
    "marisa interligi",
    "rosalia misseri",
    "gloria paul",
    "patrizia bulgari",
    "emanuela pacotto",
    "yu yu",
    "danilo fatur",
    "marco destro",
    "ugo russo",
    "anna tatangelo",
    "tao",
    "saba anglana",
    "drupi",
    "gianni giannini",
    "giuseppe masia",
    "umberto marcato",
    "valerie dore",
    "ryan paris",
    "ninni maina",
    "soul david",
    "rudy rotta",
    "ricky belloni",
    "damiano della torre",
    "andrea bocelli",
    "terry schiavo",
    "mal",
    "mario rosini",
    "laura landi",
    "leo sanfelice",
    "aida cooper",
    "etta scollo",
    "rita pavone",
    "gennaro cannavacciuolo",
    "roberto meloni",
    "lallo circosta",
    "karima",
    "noemi",
    "tina polito",
    "maurizia paradiso",
    "patrizia loreti",
    "elena presti",
    "daniela pedali",
    "ernesto tomasini",
    "franco serafini",
    "giampiero ingrassia",
    "pago",
    "giusy ferreri",
    "maria laura baccarini",
    "valentina giovagnini",
    "marco carta",
    "mario incudine",
    "mascia foschi",
    "barbara gilbo",
    "stefano bollani",
    "lisa",
    "rosanna ruffini",
    "alessandra amoroso",
    "marya",
    "attilio fontana",
    "maria nazionale",
    "graziano galatone",
    "ottavia fusco",
    "regina",
    "michel altieri",
    "giò giò rapattoni",
    "giulia luzi",
    "davide calabrese",
    "franco jadanza",
    "irene carossia",
    "taleesa",
    "italo ianne",
    "alfio lombardi",
    "silvia viscardini",
    "nancy cuomo",
    "giulietta sacco",
    "giovanna",
    "paolo martella",
    "franco dani",
    "claudia mori",
    "richard benson",
    "jessica brando",
    "roberto balocco",
    "marco mengoni",
    "gigi cifarelli",
    "giulia ottonello",
    "edda dell'orso",
    "riccardo zara",
    "lilith",
    "fratelli mancuso",
    "sabrina musiani",
    "giulia daneo lorimer",
    "serena autieri",
    "gianni drudi",
    "filippo merola",
    "valerio scanu",
    "alessandro gariazzo",
    "simona bencini",
    "carolina márquez",
    "francesca folloni",
    "graziana borciani",
    "lorenzo scuda",
    "fabio vagnarelli",
    "rino salviati",
    "emma re",
    "giovanni zarrella",
    "anna oxa",
    "maria scicolone",
    "emma marrone",
    "arisa",
    "loredana errore",
    "mirko casadei",
    "laura migliacci",
    "cecilia gayle",
    "savage",
    "kay mccarthy",
    "clara murtas",
    "stefano d'orazio",
    "alfredo cerruti",
    "eddy napoli",
    "peppe servillo",
    "anna malvica",
    "mauro ermanno giovanardi",
    "graziano facchini",
    "tiziana ghiglioni",
    "dino cassio",
    "uccio aloisi",
    "fabrizio voghera",
    "gaia ranieri",
    "gianluca vitiello",
    "danio manfredini",
    "ida rendano",
    "mariangela d'abbraccio",
    "miro sassolini",
    "yasemin sannino",
    "rosapaeda",
    "agnese claisse",
    "elisa ridolfi",
    "gianfranca montedoro",
    "lina savonà",
    "stefano picchi",
    "niky",
    "anna ranalli",
    "remo zito",
    "paolo bonfanti",
    "nello buongiorno",
    "miani",
    "mikelangelo loconte",
    "elena bonelli",
    "franca masu",
    "lucia rizzi",
    "massimo laguardia",
    "ambra lo faro",
    "luca serio bertolini",
    "luca leoni",
    "luisa de santis",
    "max paiella",
    "an'neris",
    "flavio gismondi",
    "sandy müller",
    "rosalba archilletti",
    "cristina zavalloni",
    "giorgia gueglio",
    "john de leo",
    "rosario pellecchia",
    "franco ricciardi",
    "miss xox",
    "pinguini tattici nucleari",
    "rovere",
    "aka 7even",
    "sangiovanni",
    "luigi strangis",
    "rocco hunt",
    "elettra lamborghini",
    "måneskin",
    "boomdabash",
    "fred de palma",
    "thasup",
    "tananai",
    "elodie",
    "anna",
    "rkomi",
    "ultimo",
    "alessandra amoroso",
    "marco mengoni",
    "ghali",
    "lda",
    "ana mena",
    "paky",
    "lazza",
    "mahmood",
    "lunapop",
    "gabry ponte",
    "883",
    "francesco gabbani",
    "Calcutta",
    "ligabue"
]