export const artists = [
    "frah quintale",
    "marracash", 
    "blanco", 
    "carl brave",
    "umberto tozzi",
    "giorgia",
    "michele zarrillo",
    "ivan graziani",
    "gianluca grignani",
    "fred bongusto",
    "pupo",
    "fabrizio de andré",
    "ceri",
    "CALCUTTA",
    "domenico modugno",
    "antonello venditti",
    "mia martini",
    "piero pelù",
    "luchè",
    "fabri fibra",
    "marracash",
    "jake la furia",
    "gué pequeno",
    "gué",
    "noyz narcos",
    "bassi maestro",
    "j-ax",
    "salmo",
    "emis killa",
    "clementino",
    "fedez",
    "coez",
    "gemitaiz",
    "madman",
    "luchè",
    "sfera ebbasta",
    "irama",
    "mecna",
    "ghali",
    "izi",
    "mostro",
    "rkomi",
    "shade",
    "willie peyote",
    "tedua",
    "ernia",
    "carl brave",
    "sick luke",
    "capo plaza",
    "frah quintale",
    "anastasio",
    "franco126",
    "lazza",
    "myss keta",
    "lowlow",
    "massimo pericolo",
    "tha supreme",
    "shiva",
    "nayt",
    "anna",
    "gianni bismark",
    "mr. rain",
    "geolier",
    "drefgold",
    "random",
    "vale lambo",
    "rose villain",
    "rosa chemical",
    "zoda",
    "nicola siciliano",
    "madame",
    "nerone",
    "axos",
    "roshelle",
    "alfa",
    "mambolosco",
    "pretty solero",
    "il tre",
    "bresh",
    "leon faun",
    "tredici pietro",
    "rhove",
    "elisa",
    "fabrizio de andré",
    "francesco de gregori",
    "toto cutugno",
    "riccardo fogli",
    "al bano",
    "umberto tozzi",
    "francesco renga",
    "dolcenera",
    "biagio antonacci",
    "luca carboni",
    "alex britti",
    "irene grandi",
    "ivana spagna",
    "loredana bertè",
    "raf",
    "neffa",
    "daniele silvestri",
    "max gazzè",
    "povia",
    "edoardo bennato",
    "caparezza",
    "elio e le storie tese",
    "luca dirisio",
    "simone cristicchi",
    "dargen d'amico",
    "laura pausini",
    "bugo",
    "ghemon",
    "gigi d'alessio",
    "samuel",
    "lucio dalla",
    "riccardo cocciante",
    "giuliano palma",
    "vasco rossi",
    "fabrizio moro",
    "eros ramazzotti",
    "donatella rettore",
    "nek",
    "tiziano ferro",
    "malika ayane",
    "jovanotti",
    "morgan",
    "claudio baglioni",
    "antonello venditti",
    "j-ax",
    "carmen consoli",
    "nina zilli",
    "cesare cremonini",
    "adriano celentano",
    "annalisa",
    "brunori sas",
    "iva zanicchi",
    "massimo ranieri",
    "fausto leali",
    "patty pravo",
    "fiorella mannoia",
    "raffaella carrà",
    "ornella vanoni",
    "massimo modugno",
    "lorella cuccarini",
    "babaman",
    "gianni morandi",
    "gianni celeste",
    "mina",
    "anna tatangelo",
    "gianni giannini",
    "noemi",
    "marco carta",
    "valerio scanu",
    "anna oxa",
    "maria scicolone",
    "emma marrone",
    "arisa",
    "pinguini tattici nucleari",
    "rovere",
    "aka 7even",
    "sangiovanni",
    "rocco hunt",
    "elettra lamborghini",
    "måneskin",
    "boomdabash",
    "fred de palma",
    "tananai",
    "elodie",
    "anna",
    "rkomi",
    "ultimo",
    "alessandra amoroso",
    "marco mengoni",
    "ghali",
    "ana mena",
    "lazza",
    "mahmood",
    "lunapop",
    "gabry ponte",
    "883",
    "francesco gabbani",
    "Calcutta",
    "ligabue",
    "Elettra Lamborghini",
    "Lorenzo Fragola",
    "Laura Pausini",
    "Marco Mengoni",
    "Takagi & Ketra",
    "Irama",
    "Ultimo",
    "Ariete",
    ""
]